In [1]:
import numpy as np

#### Questions

> A. Peform both vector addition and subtraction for the folowing
- [2,44,8] and [3,9,22]
- [0, 0001] and [-12.8, 09090]

> B. Peform bith Scalar-Vector Multiplication and Division for the following:
- [4,7,8] and 0.9
- [80,9,7,2,1,22,0] and 1

> C. Perform both Matrix-Scalar Multiplication and DIvision for the following:
- [[2,3,1],[4,1,0]] and 3
- [[3,0.1, 80, 9], [7,2,1,22]] and 0.02

> D. Perform Matrix-Matrix Multiplication for the following:
- [[1,3,2], [2,1,4]] and [[3,0.1,4], [5,1,0]]

> E. Generate an identity Matrix of the following shape: 
-  (8,8)

#### Solutions

A. 

In [5]:
add_a1 = np.array([2,44,8]) + np.array([3,9,22])
sub_a1 = np.array([2,44,8]) - np.array([3,9,22])

In [31]:
print(add_a1)
print(sub_a1)

[ 5 53 30]
[ -1  35 -14]


In [6]:
add_a2 = np.array([0, 1]) + np.array([-12.8, 9090])
sub_a2 = np.array([0, 1]) - np.array([-12.8, 9090])

In [30]:
print(add_a2)
print(sub_a2)

[ -12.8 9091. ]
[   12.8 -9089. ]


B.

In [28]:
mul_b1 =    np.array([4,7,8]) * 0.9
div_b1 =    np.array([4,7,8])/0.9

In [29]:
print(mul_b1)
print(div_b1)

[3.6 6.3 7.2]
[4.44444444 7.77777778 8.88888889]


In [9]:
mul_b2 =   np.array([80,9,7,2,1,22,0]) * 1
div_b2 =   np.array([80,9,7,2,1,22,0])/1

In [26]:
print(mul_b2)
print(div_b2)

[80  9  7  2  1 22  0]
[80.  9.  7.  2.  1. 22.  0.]


C

In [13]:
mul_c1 = np.array([[2,3,1],[4,1,0]]) * 3
div_c1 = np.array([[2,3,1],[4,1,0]]) / 3

In [25]:
print(mul_c1)
print(div_c1)

[[ 6  9  3]
 [12  3  0]]
[[0.66666667 1.         0.33333333]
 [1.33333333 0.33333333 0.        ]]


In [14]:
mul_c2 = np.array([[3,0.1, 80, 9], [7,2,1,22]]) * 0.02
div_c2 = np.array([[3,0.1, 80, 9], [7,2,1,22]]) /0.02

In [23]:
print(mul_c2)
print(div_c2)

[[0.06  0.002 1.6   0.18 ]
 [0.14  0.04  0.02  0.44 ]]
[[ 150.    5. 4000.  450.]
 [ 350.  100.   50. 1100.]]


D

In [22]:
mul_d= np.array([[1,3,2], [2,1,4]]) * np.array([[3,0.1,4], [5,1,0]])
mul_d

array([[ 3. ,  0.3,  8. ],
       [10. ,  1. ,  0. ]])

E

In [21]:
e_eye = np.eye(8,8)
e_eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])